# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Install system dependencies
RUN apk add --no-cache build-base libffi-dev openssl-dev

WORKDIR /app

# Copy the entire repository
COPY . .

# Upgrade pip and install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir .

# Expose port 8000 (default for HTTP mode)
EXPOSE 8000

# Set the entrypoint and default command
ENTRYPOINT ["python", "-m", "paper_search_mcp.server"]

# Add --server to the docker run command to run as HTTP server
CMD [] 
