# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Install system dependencies
RUN apk add --no-cache build-base libffi-dev openssl-dev

WORKDIR /app

# Copy the entire repository
COPY . .

# Upgrade pip and install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir .

# Expose port 8000 (default for HTTP mode)
EXPOSE 8000

# Set the entrypoint and default command
ENTRYPOINT ["python", "-m", "paper_search_mcp.server"]

# Environment variables to control server mode:
# SERVER=true (or 1, yes, on) to run as HTTP server
# PORT=8000 (default port for HTTP server)
# HOST=0.0.0.0 (default host for HTTP server)
# NCBI_API_KEY=your_api_key (optional, for higher PubMed rate limits)
CMD [] 
